### ISSUE TITLE
Change some methods to private?

### ISSUE THREAD

**Issue by zaazz** [ggorlen/cs130a#16]
Just to meet the requirements of the assignment, I'm wondering if we should have a few more private functions. We're using most of our functions in inherited classes, but there might be a few that aren't needed outside of the class. I noticed Ted has setSides in the Rhombus class as private. Are there any others?
- Julie Ann

**Comment by ggorlen** [comment]
Square class looks great!  I hope it makes the inheritance concept clear.

Yep, it's a good point I had in mind as well re: private methods.  I can't think of any new methods that should be private, so my plan was to move isVerticesArray back into Polygon as a private helper method as it was originally.  Circle and Rectangle don't use this method, so it seems reasonable.  Some of those Polygon calculations iterate over the vertices in a similar way, so it's common practice to abstract that into a private function that accepts a callback, but it's just too much of a stretch at this point in the design--it's as bad practice to over-abstract just as it is to under-abstract.  So I'll go ahead and make this change and close the issue for now.

Rhombus class needs work--that's an outstanding issue.  Now that we have Polygon, we should technically re-write Rhombus to subclass it, but I was waiting on Ted before messing with his contribution.  The goal is to get the class so that you can only make Rhombuses with it--let's think about what characteristics are unique to Rhombuses?  Part of the problem here is that we really want a RegularPolygon subclass of Polygon... and then we're probably in overkill zone, so it seems like we might need to jettison Rhombus class but chalk it up as a learning experience and excellent step towards building a Polygon class, which I wrote by modifying Rhombus.

So is there anything else we want to do with this project during the final day?  I'm pretty proud of it, so it's tempting to give it a small UI and some polish so a visitor can make their own shapes, but it's all up to the group.  Doing more subclasses might involve math, which would also be educational, or we can absolutely leave it as is after dealing with Rhombus, since I think we've more than accomplished the task.
Greg
